### ISSUE TITLE
Missing cairo-quartz in recent macOS packages

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cairo-feedstock#34]
In the `cairo-1.14.10-0.tar.bz2` package for `osx-64`, the files `cairo-quartz.pc` and `cairo-quartz-font.pc` were included. However in the `cairo-1.14.10-he56eebe_1.tar.bz2` package or the `cairo-1.14.12-he56eebe_0.tar-1.bz2` package for `osx-64` these files are gone. As a result things like `gtk2` don't find them and fail to build.

Edit: FTR here are the differences ( https://github.com/conda-forge/cairo-feedstock/compare/014790c56d33b864c6b57703e865e2ed30889d2b...8df80fb2d244ddcb9230e04c6a430a90feb6dff9 ).

xref: https://github.com/conda-forge/gtk2-feedstock/pull/1

**Comment by pkgw** [comment]
Like one aspect of #32, the problem here is because the latest package of `fontconfig`, the 2.13 series, now depends on `libuuid`. The UUID headers provided by this package shadow the system headers, leading to a compilation failure with `ApplicationServices.h`, which causes the Cairo configure script not to enable the Quartz backend on OS X ([example](https://travis-ci.org/conda-forge/cairo-feedstock/builds/400572472#L664)). The current test suite doesn't flag this as a problem.

I will try to think about fixes, but suggestions are most welcome!

**Comment by pkgw** [comment]
Well, it certainly would not have been obvious to me that adding libuuid as a dep would cause problems, but in retrospect it seems that it is so low in the dependency stack that it can cause problems when relying on slightly higher-level system libraries.

It looks like a workaround for this particular issue is just to `rm -rf $PREFIX/include/uuid` before the build on macOS. I am not a huge fan of that. Maybe there is a way to get rid of that uuid dep in fontconfig — I'll look at the logs.

**Comment by jakirkham** [comment]
Ha! It's a [bug in `fontconfig` on macOS]( https://bugs.freedesktop.org/show_bug.cgi?id=105366 ). Now kicking myself for not looking more deeply into this. One sec while I get a PR together.

**Comment by pkgw** [comment]
Cool (sort of). It sounds like it is Correct™ to publish a new fontconfig build that strips the libuuid dep on macOS. (Although it is worth emphasizing that, based on #32, it is possible for the dep to cause problems on Linux as well, if a package tries to link with a system library that depends on the system libuuid.)

Once the new fontconfig is available, I believe that the thing to do would be to put in a Cairo PR that bumps the build number and adds the following test lines to try to prevent reoccurrences:

```
  - test -f $PREFIX/lib/pkgconfig/cairo-quartz.pc  # [osx]
  - test -f $PREFIX/lib/pkgconfig/cairo-xlib.pc  # [linux]
```

**Comment by jakirkham** [comment]
Would you rather we strip `libuuid` from both macOS and Linux? If so, SGTM.

Yes, a test in `cairo` would be good. If you can think of one for `fontconfig`, am happy to add that as well.

**Comment by pkgw** [comment]
@jakirkham I *think* that keeping the `libuuid` dep on Linux is the way to go, for now at least. These issues are making it seem as if maybe `libuuid` should start getting treated as a system library on both Linux on macOS — which would imply that we should stop providing it — but that would be a substantially bigger policy change.

Relatedly, I don't think there's anything in particular to test in `fontconfig`. If the problem is that pulling in `libuuid` on macOS is generically bad, `fontconfig` would not be the place to test for that.
